export { default as BriefingPage } from './pages/BriefingPage'
export { default as MayorDashboardPage } from './pages/MayorDashboardPage'
export { default as OperationsPage } from './pages/OperationsPage'
export { default as IncidentPage } from './pages/IncidentPage'
export { default as HistoryPage } from './pages/HistoryPage'
export { default as ScenariosPage } from './pages/ScenariosPage'
export { default as DeputiesPage } from './pages/DeputiesPage'
export { default as RegulationsPage } from './pages/RegulationsPage'
export { default as PlaceholderPage } from './pages/PlaceholderPage'
export { SchoolsKindergartensPage } from './schools-kindergartens'
