import type { LiveSourceMode, SigmaSourceRegistryEntry, SourceRegistryEntry } from '../types'

const now = undefined
const opendataBaseUrl = (import.meta.env.VITE_OPENDATA_BASE_URL || 'https://opendata.novo-sibirsk.ru').replace(/\/$/, '')

export const sigmaSourceRegistry: SigmaSourceRegistryEntry[] = [
  {
    id: 'source-051',
    name: '051 — отключения ЖКХ',
    kind: 'html',
    ttlMs: 30 * 60 * 1000,
    sourceUrls: [import.meta.env.VITE_051_URL || 'https://051.novo-sibirsk.ru/SitePages/off.aspx'],
    license: 'Официальный городской HTML-интерфейс',
    refreshMode: 'hybrid',
    dataCategory: 'real',
    supportsHistory: true,
    supportsMap: true,
    supportsAskSigma: true,
    status: 'idle',
    lastUpdated: now,
    enabled: true,
    directions: ['utilities', 'city-services'],
  },
  {
    id: 'source-opendata-stops',
    name: 'OpenData — остановки',
    kind: 'csv',
    ttlMs: 24 * 60 * 60 * 1000,
    sourceUrls: [opendataBaseUrl],
    license: 'Открытые данные мэрии Новосибирска',
    refreshMode: 'snapshot',
    dataCategory: 'reference',
    supportsHistory: false,
    supportsMap: true,
    supportsAskSigma: true,
    status: 'idle',
    enabled: true,
    directions: ['transport', 'roads'],
  },
  {
    id: 'source-opendata-schools', name: 'OpenData — школы', kind: 'csv', ttlMs: 24 * 60 * 60 * 1000, sourceUrls: [opendataBaseUrl], license: 'Открытые данные мэрии Новосибирска', refreshMode: 'snapshot', dataCategory: 'reference', supportsHistory: false, supportsMap: true, supportsAskSigma: true, status: 'idle', enabled: true, directions: ['education', 'social'] },
  { id: 'source-opendata-kindergartens', name: 'OpenData — детские сады', kind: 'csv', ttlMs: 24 * 60 * 60 * 1000, sourceUrls: [opendataBaseUrl], license: 'Открытые данные мэрии Новосибирска', refreshMode: 'snapshot', dataCategory: 'reference', supportsHistory: false, supportsMap: true, supportsAskSigma: true, status: 'idle', enabled: true, directions: ['education', 'social'] },
  { id: 'source-opendata-libraries', name: 'OpenData — библиотеки', kind: 'csv', ttlMs: 24 * 60 * 60 * 1000, sourceUrls: [opendataBaseUrl], license: 'Открытые данные мэрии Новосибирска', refreshMode: 'snapshot', dataCategory: 'reference', supportsHistory: false, supportsMap: true, supportsAskSigma: true, status: 'idle', enabled: true, directions: ['culture', 'social'] },
  { id: 'source-opendata-pharmacies', name: 'OpenData — аптеки', kind: 'csv', ttlMs: 24 * 60 * 60 * 1000, sourceUrls: [opendataBaseUrl], license: 'Открытые данные мэрии Новосибирска', refreshMode: 'snapshot', dataCategory: 'reference', supportsHistory: false, supportsMap: true, supportsAskSigma: true, status: 'idle', enabled: true, directions: ['medical', 'social'] },
  { id: 'source-opendata-sport-grounds', name: 'OpenData — спортивные площадки', kind: 'csv', ttlMs: 24 * 60 * 60 * 1000, sourceUrls: [opendataBaseUrl], license: 'Открытые данные мэрии Новосибирска', refreshMode: 'snapshot', dataCategory: 'reference', supportsHistory: false, supportsMap: true, supportsAskSigma: true, status: 'idle', enabled: true, directions: ['sport', 'social'] },
  { id: 'source-opendata-sport-orgs', name: 'OpenData — спортивные организации', kind: 'csv', ttlMs: 24 * 60 * 60 * 1000, sourceUrls: [opendataBaseUrl], license: 'Открытые данные мэрии Новосибирска', refreshMode: 'snapshot', dataCategory: 'reference', supportsHistory: false, supportsMap: true, supportsAskSigma: true, status: 'idle', enabled: true, directions: ['sport', 'social'] },
  { id: 'source-opendata-culture', name: 'OpenData — учреждения культуры', kind: 'csv', ttlMs: 24 * 60 * 60 * 1000, sourceUrls: [opendataBaseUrl], license: 'Открытые данные мэрии Новосибирска', refreshMode: 'snapshot', dataCategory: 'reference', supportsHistory: false, supportsMap: true, supportsAskSigma: true, status: 'idle', enabled: true, directions: ['culture', 'social'] },
  { id: 'source-opendata-parking', name: 'OpenData — парковки', kind: 'csv', ttlMs: 24 * 60 * 60 * 1000, sourceUrls: [opendataBaseUrl], license: 'Открытые данные мэрии Новосибирска', refreshMode: 'snapshot', dataCategory: 'reference', supportsHistory: false, supportsMap: true, supportsAskSigma: true, status: 'idle', enabled: true, directions: ['transport', 'city-services'] },
  { id: 'source-opendata-construction-permits', name: 'OpenData — разрешения на строительство', kind: 'csv', ttlMs: 24 * 60 * 60 * 1000, sourceUrls: [`${opendataBaseUrl}/pass.aspx?ID=124`], license: 'Открытые данные мэрии Новосибирска', refreshMode: 'hybrid', dataCategory: 'real', supportsHistory: true, supportsMap: true, supportsAskSigma: true, status: 'idle', enabled: true, directions: ['construction'] },
  { id: 'source-opendata-construction-commissioned', name: 'OpenData — ввод в эксплуатацию', kind: 'csv', ttlMs: 24 * 60 * 60 * 1000, sourceUrls: [`${opendataBaseUrl}/pass.aspx?ID=125`], license: 'Открытые данные мэрии Новосибирска', refreshMode: 'hybrid', dataCategory: 'real', supportsHistory: true, supportsMap: true, supportsAskSigma: true, status: 'idle', enabled: true, directions: ['construction'] },
  {
    id: 'source-openmeteo-air',
    name: 'Open-Meteo — качество воздуха',
    kind: 'api',
    ttlMs: 15 * 60 * 1000,
    sourceUrls: ['https://air-quality-api.open-meteo.com/v1/air-quality'],
    license: 'Open-Meteo / CC BY 4.0',
    refreshMode: 'hybrid',
    dataCategory: 'real',
    supportsHistory: true,
    supportsMap: true,
    supportsAskSigma: true,
    status: 'idle',
    enabled: true,
    directions: ['ecology'],
  },
  {
    id: 'source-openmeteo-weather',
    name: 'Open-Meteo — погода',
    kind: 'api',
    ttlMs: 15 * 60 * 1000,
    sourceUrls: ['https://api.open-meteo.com/v1/forecast'],
    license: 'Open-Meteo / CC BY 4.0',
    refreshMode: 'hybrid',
    dataCategory: 'real',
    supportsHistory: true,
    supportsMap: true,
    supportsAskSigma: true,
    status: 'idle',
    enabled: true,
    directions: ['ecology', 'roads'],
  },
  {
    id: 'source-cityair',
    name: 'CityAir API',
    kind: 'api',
    ttlMs: 15 * 60 * 1000,
    sourceUrls: ['https://cityair.example/api'],
    license: 'API key / зависит от инсталляции',
    refreshMode: 'manual',
    dataCategory: 'real',
    supportsHistory: true,
    supportsMap: true,
    supportsAskSigma: true,
    status: 'idle',
    enabled: Boolean(import.meta.env.VITE_CITYAIR_API_KEY),
    directions: ['ecology'],
  },
  {
    id: 'source-overpass-cameras',
    name: 'OSM Overpass — камеры ПДД',
    kind: 'overpass',
    ttlMs: 7 * 24 * 60 * 60 * 1000,
    sourceUrls: ['https://overpass-api.de/api/interpreter'],
    license: 'OpenStreetMap ODbL',
    refreshMode: 'snapshot',
    dataCategory: 'reference',
    supportsHistory: false,
    supportsMap: true,
    supportsAskSigma: true,
    status: 'idle',
    enabled: true,
    directions: ['safety', 'roads'],
  },
  {
    id: 'source-overpass-medical',
    name: 'OSM Overpass — медучреждения',
    kind: 'overpass',
    ttlMs: 72 * 60 * 60 * 1000,
    sourceUrls: ['https://overpass-api.de/api/interpreter'],
    license: 'OpenStreetMap ODbL',
    refreshMode: 'snapshot',
    dataCategory: 'reference',
    supportsHistory: false,
    supportsMap: true,
    supportsAskSigma: true,
    status: 'idle',
    enabled: true,
    directions: ['medical', 'social'],
  },
  {
    id: 'source-osm-boundaries',
    name: 'OSM — административные границы районов',
    kind: 'static',
    ttlMs: 30 * 24 * 60 * 60 * 1000,
    sourceUrls: ['https://www.openstreetmap.org'],
    license: 'OpenStreetMap ODbL',
    refreshMode: 'manual',
    dataCategory: 'reference',
    supportsHistory: false,
    supportsMap: true,
    supportsAskSigma: false,
    status: 'idle',
    enabled: true,
    directions: ['city-services'],
  },
  {
    id: 'source-traffic-index',
    name: 'Sigma — traffic index',
    kind: 'derived',
    ttlMs: 15 * 60 * 1000,
    sourceUrls: ['sigma://derived/traffic-index'],
    license: 'Sigma calculated',
    refreshMode: 'runtime',
    dataCategory: 'calculated',
    supportsHistory: true,
    supportsMap: true,
    supportsAskSigma: true,
    status: 'idle',
    enabled: true,
    directions: ['transport', 'roads'],
  },
]

export const sourceRegistry: Record<'power051' | 'constructionPermits' | 'constructionCommissioned' | 'constructionActive', SourceRegistryEntry> = {
  power051: {
    key: '051',
    title: '051 — отключения ЖКХ',
    sourceUrl: import.meta.env.VITE_051_URL || 'https://051.novo-sibirsk.ru/SitePages/off.aspx',
    snapshotPath: '/live-data/051/latest.json',
    ttlMinutes: 30,
  },
  constructionPermits: {
    key: 'opendata',
    title: 'OpenData — разрешения на строительство',
    sourceUrl: `${opendataBaseUrl}/pass.aspx?ID=124`,
    snapshotPath: '/live-data/opendata/construction-permits.json',
    ttlMinutes: 60 * 24,
  },
  constructionCommissioned: {
    key: 'opendata',
    title: 'OpenData — ввод в эксплуатацию',
    sourceUrl: `${opendataBaseUrl}/pass.aspx?ID=125`,
    snapshotPath: '/live-data/opendata/construction-commissioned.json',
    ttlMinutes: 60 * 24,
  },
  constructionActive: {
    key: 'opendata',
    title: 'OpenData — активные стройки',
    sourceUrl: `${opendataBaseUrl}/pass.aspx?ID=124`,
    snapshotPath: '/live-data/opendata/construction-active.json',
    ttlMinutes: 60 * 24,
  },
}

export const getSigmaSource = (id: string) => sigmaSourceRegistry.find((entry) => entry.id === id)

export const getLiveSourceMode = (): LiveSourceMode => {
  const raw = String(import.meta.env.VITE_SOURCE_MODE || 'hybrid').toLowerCase()
  if (raw === 'mock' || raw === 'live' || raw === 'hybrid') return raw
  return 'hybrid'
}

export const isRuntimeLiveFetchEnabled = (): boolean => String(import.meta.env.VITE_ENABLE_RUNTIME_LIVE_FETCH || 'true') === 'true'
